### ISSUE TITLE
Use of deprecated package "logdna"

### ISSUE THREAD

**Issue by frostmar** [logdna/logdna-bunyan#17]
I see that package `logdna` has been deprecated recently:
> logdna has been renamed to @logdna/logger. Please install the latest version of @logdna/logger instead of logdna

Will this package be updated to depend on `@logdna/logger`? Or is there a replacement for this package we should use instead?

Thanks.

**Comment by smusali** [comment]
@frostmar, thanks for reporting this! The package got updated in #19 and released as `v2.0.0`
