### ISSUE TITLE
Use latest logdna version

### ISSUE THREAD

**Issue by MartinRoss-IBM** [logdna/logdna-bunyan#6]
The logdna-bunyan library is currently using logdna ^2.0.0, but that dependency is now on v3.

Can logdna-bunyan move to use logdna ^3.0.0 to pick up any new fixes and features?

**Comment by respectus** [comment]
@MartinRoss-IBM Thanks for the reminder, logdna-bunyan module version v 1.1.0 now depends on logdna ^3.0.0
