### ISSUE TITLE
Regression in logdna-bunyan@1.1.5

### ISSUE THREAD

**Issue by gr2m** [logdna/logdna-bunyan#9]
A closing bracket is missing at 

https://github.com/logdna/logdna-bunyan/blob/37ae1736beb24d2207f1dec0771035c131b01571/index.js#L24-L26

which results in

> SyntaxError: missing ) after argument list

**Comment by smusali** [comment]
Thanks for reporting, @gr2m! Fixed in [`v1.1.6`](https://www.npmjs.com/package/logdna-bunyan)

**Comment by gr2m** [comment]
My pleasure :) 

Maybe add a basic test which would throw in case of syntax errors to prevent that from happening in future?

**Comment by smusali** [comment]
@gr2m you are right and we are currently on the process of building integration testing for all customer-facing integrations - this was just unexpected accident - we may stop releasing newer versions till we finish up building test cases.
